# Generated by Django 5.0.2 on 2024-04-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('past', 'Past'), ('present', 'Present'), ('future', 'Future')], max_length=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name=''),
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
