# Generated by Django 5.0.2 on 2024-05-23 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackapi', '0004_readingprogress_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='reading_progress',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_text',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='chapter_number',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='trackapi.book')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='chapter',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='trackapi.chapter'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ReadingProgress',
        ),
    ]
